# Configuration for mqtt2ntfy in Docker environment
mqtt:
  # MQTT broker URL (using Docker service name)
  broker: "tcp://mosquitto:1883"

  # MQTT topic to subscribe to
  topic: "test/messages"

ntfy:
  # Ntfy server URL (using Docker service name and predefined topic)
  url: "http://ntfy:80/mqtt2ntfy-test"

# Heartbeat configuration for e2e testing
heartbeat:
  port: 2085
