# Example configuration for mqtt2ntfy
# Copy this file to config.yaml and update the values
#
# All values can be overridden with command-line flags or environment variables
# Precedence: flags > environment variables > config file

mqtt:
  # MQTT broker URL - protocol and port are optional
  # Examples: "localhost", "localhost:1884", "tcp://localhost:1883", "ssl://mqtt.example.com:8883"
  # Defaults: protocol=tcp://, port=1883
  broker: "localhost"

  # MQTT topic to subscribe to
  # For regular topics: "home/sensors/temperature"
  # For wildcard topics: "home/sensors/#" (uses last part as ntfy topic)
  topic: "home/sensors/temperature"

  # Optional: MQTT username for authentication
  # username: "your-mqtt-username"

  # Optional: MQTT password for authentication
  # password: "your-mqtt-password"

  # Optional: MQTT connection timeout (default: 30s)
  # connect_timeout: "30s"

  # Optional: MQTT ping timeout (default: 10s)
  # ping_timeout: "10s"

ntfy:
  # Ntfy server URL
  # For regular topics: "https://ntfy.sh/your-topic-name"
  # For wildcard topics: "https://ntfy.sh" (base URL only)
  url: "https://ntfy.sh/your-topic-name"

  # Optional: Authentication token for Ntfy (if required)
  # auth_token: "your-ntfy-auth-token"

  # Optional: Message priority (1-5, default: 3)
  # priority: "3"

  # Optional: HTTP request timeout (default: 10s)
  # timeout: "10s"

  # Optional: Maximum number of retry attempts for failed requests (default: 3)
  # max_retries: 3

   # Optional: Initial delay between retry attempts with exponential backoff (default: 1s)
   # retry_delay: "1s"

heartbeat:
  # Optional: URL to send heartbeats to (e.g., Uptime Kuma push URL)
  # If set, heartbeats will be sent to this URL
  # url: "https://uptimekuma.example.com:9001/api/push/1234abcd?status=up&msg=OK&ping="

  # Optional: Interval between heartbeats (default: 30s)
  # interval: "30s"

  # Optional: Liveness threshold - if no heartbeat sent within this time, considered unhealthy (default: 60s)
  # liveness_threshold: "60s"

  # Optional: Port for health endpoint server (default: 8888)
  # If set to a non-zero value, the health endpoint server will be started
  # port: 8888

